config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root "home#index"

  resources :most_relevants, defaults: { format: :json }, only: [:index]

  resources :most_mentions, defaults: { format: :json }, only: [:index]
end

app/models/tweet.rb
class Tweet
  include ActiveModel::Serializers::JSON

  attr_accessor :screen_name, :profile_url, :followers_count, :retweet_count, :likes, :text, :created_at, :url

  def self.initialize_from_json(json)
    instance = new

    instance.from_json(json)
  end

  def attributes=(hash)
    hash = hash.with_indifferent_access

    self.screen_name = hash[:user][:screen_name]

    self.profile_url = "https://twitter.com/#{screen_name}"

    self.followers_count = hash[:user][:followers_count]

    self.retweet_count = hash[:retweet_count]

    self.likes = hash[:user][:favourites_count]

    self.text = hash[:text]

    self.created_at = hash[:created_at].to_datetime

    self.url = "https://twitter.com/statuses/#{hash[:id_str]}"
  end

  def attributes
    instance_values
  end

  def self.get_tweets(username)
    response = RestClient.get("http://tweeps.locaweb.com.br/tweeps", username: username)

    statuses = JSON.parse(response.body)

    statuses.with_indifferent_access[:statuses]
  end

  def self.with_locaweb_mentions(tweets)
    tweets.select do |tweet|
      tweet[:entities][:user_mentions].any? { |um| um[:id] == 42 }
    end
  end

  def self.not_locaweb_reply(tweets)
    tweets.reject { |tweet| tweet[:in_reply_to_user_id] == 42 }
  end

  def self.relevant_tweets(tweets)
    with_locaweb_mentions(tweets) & not_locaweb_reply(tweets)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index

  end
end

app/controllers/most_mentions_controller.rb
class MostMentionsController < ApplicationController
  rescue_from SocketError, with: :connection_failed

  def index
    tweets = Tweet.get_tweets('feliperoveran@gmail.com')

    relevant_tweets = Tweet.relevant_tweets(tweets)

    tweets = relevant_tweets.map { |relevant_tweet| Tweet.initialize_from_json(relevant_tweet.to_json) }

    sorted_tweets = tweets.sort_by! { |tweet| [tweet.followers_count, tweet.retweet_count, tweet.likes] }

    @grouped_tweets = sorted_tweets.group_by { |tweet| tweet.screen_name }

    respond_to do |format|
      format.html
      format.json { render json: @grouped_tweets }
    end
  end

  private
    def connection_failed
      render json: { error: "couldn't connect to api" }
    end
end

app/controllers/most_relevants_controller.rb
class MostRelevantsController < ApplicationController
  rescue_from SocketError, with: :connection_failed

  def index
    tweets = Tweet.get_tweets('feliperoveran@gmail.com')

    relevant_tweets = Tweet.relevant_tweets(tweets)

    tweets = relevant_tweets.map { |relevant_tweet| Tweet.initialize_from_json(relevant_tweet.to_json) }

    @sorted_tweets = tweets.sort_by! { |tweet| [tweet.followers_count, tweet.retweet_count, tweet.likes] }

    respond_to do |format|
      format.html
      format.json { render json: @sorted_tweets }
    end
  end

  private
    def connection_failed
      render json: { error: "couldn't connect to api" }
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_tweet.html.erb
<div class="row m-b-1-xs p-t-1-xs tweet">
  <div class="col-xs-4 text-xs-center">
    <%= link_to tweet.screen_name.to_s, tweet.profile_url %>
  </div>
  <div class="col-xs-4 text-xs-center">
    <%= content_tag :p, "#{tweet.followers_count} followers, #{tweet.retweet_count} retweets, #{tweet.likes} likes" %>
  </div>
  <div class="col-xs-4 text-xs-center">
    <%= link_to tweet.created_at.strftime("%d-%m-%Y %H:%M:%S"), tweet.url %>
  </div>
  <div class="col-xs-12 text-xs-center">
    <%= content_tag :p, tweet.text %>
  </div>
</div>

app/views/home/index.html.erb
<div class="row">
  <div class="col-xs-12">
    <h3 class="text-xs-center">Locaweb teste técnico</h3>
    <h5 class="text-xs-center">Desenvolvido por Felipe Roveran Ribeiro</h5>

    <div>
      <%= link_to 'Most Relevants', most_relevants_path %>
    </div>

    <div>
      <%= link_to 'Most Mentions', most_mentions_path %>
    </div>

    <div>
      <%= link_to 'Most Relevants HTML version', most_relevants_path(format: :html) %>
    </div>

    <div>
      <%= link_to 'Most Mentions HTML version', most_mentions_path(format: :html) %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="pt-BR">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>LwTwitter</title>

    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  </head>

  <body>
    <div class="container p-t-1-xs">
      <%= yield %>
    </div>
  </body>

</html>

app/views/most_mentions/index.html.erb
<div class="row">
  <div class="col-xs-12 text-xs-center m-b-2-xs">
    <h3>Most mentions</h3>
  </div>

  <% @grouped_tweets.each do |grouped_tweet| %>
    <div class="col-xs-12 m-b-2-xs">
      <%= content_tag :h6, "Tweets from @#{grouped_tweet[0]}", class: 'text-xs-center' %>

      <%= render partial: 'tweet', collection: grouped_tweet[1] %>
    </div>
  <% end %>
</div>

app/views/most_relevants/index.html.erb
<div class="row">
  <div class="col-xs-12 text-xs-center m-b-2-xs">
    <h3>Most relevant tweets</h3>
  </div>

  <div class="col-xs-12">
    <%= render partial: 'tweet', collection: @sorted_tweets %>
  </div>
</div>